import { randomBytes, randomUUID } from "node:crypto";
import { gzipSync } from "node:zlib";
import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { makeLoaf } from "./loaf.js";
import { encodePngSpeak } from "./pngspeak.js";
import { encodeGptgif } from "./gptgif.js";
import { encodeGptgifV4 } from "./gptgif-v4.js";
import { decoderGuides } from "./decoder-challenge-guides.js";

export const ChallengeBody = z.object({
  format: z.enum(["loaf", "pngspeak", "gptgif", "gptgif-v4"]),
  guidance: z.enum(["guided", "independent"]).default("guided"),
  payload: z.enum(["text", "binary"]).default("text"),
}).strict();
export const ChallengeParams = z.object({ id: z.string().uuid() });
export const ChallengeKitBody = z.object({ ids: z.array(z.string().uuid()).min(1).max(4) }).strict();
export const ChallengeAnswer = z.object({
  hex: z.string().max(8192).regex(/^(?:[0-9a-fA-F]{2})*$/, "Answer must contain complete hexadecimal byte pairs, without spaces."),
}).strict();

const formats = {
  loaf: { label: "LoaF", extension: "loaf", mime: "text/plain", encode: (bytes: Buffer) => Buffer.from(makeLoaf([{ name: "payload.bin", content: bytes, mtime: new Date(0) }])) },
  pngspeak: { label: "PngSpeak", extension: "pngspk.png", mime: "image/png", encode: (bytes: Buffer) => encodePngSpeak(bytes) },
  gptgif: { label: "Original gptgif", extension: "gptgif.gif", mime: "image/gif", encode: (bytes: Buffer) => encodeGptgif([bytes]) },
  "gptgif-v4": { label: "gptgif v4", extension: "gptgif-v4.gif", mime: "image/gif", encode: (bytes: Buffer) => encodeGptgifV4([bytes], { fontSeed: randomBytes(4).readUInt32LE(), paletteSeed: randomBytes(4).readUInt32LE() }) },
};

// Per-app, bounded, ephemeral answer keys. Session changes invalidate access.
// Only freshly generated bytes are encoded; no client paths or codec options.
export function registerDecoderChallengeRoutes(app: FastifyInstance, scope: () => string) {
  const challenges = new Map<string, { scope: string; expected: Buffer; artifact: Buffer; format: keyof typeof formats; expiresAt: number; prompt: string }>();
  app.addHook("onClose", async () => { challenges.clear(); });
  app.post("/api/decoder-challenges", { bodyLimit: 1024, config: { rateLimit: { max: 20, timeWindow: "1 minute" } } }, async (req, reply) => {
    const body = ChallengeBody.parse(req.body);
    const owner = scope();
    for (const [id, challenge] of challenges) {
      if (challenge.expiresAt <= Date.now() || challenge.scope !== owner) challenges.delete(id);
    }
    // Refuse at capacity rather than silently evicting another open challenge.
    if (challenges.size >= 64) return reply.code(429).send({ error: "Challenge shelf is full. Try again after an older challenge expires." });
    const id = randomUUID();
    const expected = body.payload === "text"
      ? Buffer.from(`Mirror decoder expedition\nDiscovery: ${randomBytes(16).toString("hex")}\nKeep every byte: café, stars ✨, and this final newline.\n`, "utf8")
      : randomBytes(128);
    const format = formats[body.format];
    const artifact = format.encode(expected);
    const expiresAt = Date.now() + 24 * 60 * 60 * 1000;
    const filename = `decoder-${id}.${format.extension}`;
    const transport = gzipSync(artifact).toString("base64");
    const prompt = `Mirror decoder challenge ${id}\nFormat: ${format.label}. Task: recover the exact original payload bytes.\n` +
      `Use code execution if available. Do not guess or claim execution you cannot perform. Explain your method.\n` +
      `The artifact is transported below as base64(gzip(file bytes)) to preserve it exactly in this text prompt.\n` +
      `First base64-decode and gzip-decompress the transport into ${filename}; THEN decode the ${format.label} format itself. The transport is not the answer.\n` +
      (body.guidance === "guided" ? `\nFORMAT GUIDE\n${decoderGuides[body.format]}\n` : `\nNo decoding guide is included. Investigate the named format and the artifact. For LoaF, the target is the content of payload.bin.\n`) +
      `\nFinish with exactly one line, replacing HEX with the complete recovered bytes as lowercase hex:\nMIRROR_ANSWER_${id}: HEX\n` +
      `Do not substitute a hash, explanation, or the encoded file. Mirror will check against a server-held answer key.\n\nBEGIN_GZIP_BASE64\n${transport}\nEND_GZIP_BASE64`;
    challenges.set(id, { scope: owner, expected, artifact, format: body.format, expiresAt, prompt });
    reply.header("cache-control", "no-store");
    return { id, format: body.format, label: format.label, guidance: body.guidance, payload: body.payload, filename, artifactBytes: artifact.length, prompt, expiresAt };
  });
  app.post("/api/decoder-challenges/kit", { bodyLimit: 1024 }, async (req, reply) => {
    const { ids } = ChallengeKitBody.parse(req.body);
    const entries = [];
    for (const id of ids) {
      const challenge = challenges.get(id);
      if (!challenge || challenge.scope !== scope() || challenge.expiresAt <= Date.now()) {
        return reply.code(404).send({ error: "Challenge expired or unavailable. Generate a new one." });
      }
      const format = formats[challenge.format];
      const prefix = `${challenge.format}-${id}`;
      // The separate guide is for the user: independent-mode prompts still
      // withhold it. No kit includes the expected plaintext or answer bytes.
      entries.push(
        { name: `${prefix}/decoder-${id}.${format.extension}`, content: challenge.artifact },
        { name: `${prefix}/prompt.txt`, content: Buffer.from(challenge.prompt) },
        { name: `${prefix}/format-guide.txt`, content: Buffer.from(decoderGuides[challenge.format]) },
        { name: `${prefix}/README.txt`, content: Buffer.from(`${format.label} decoder challenge ${id}\n\nPaste prompt.txt into ChatGPT, or attach prompt.txt and ask GPT to solve the challenge described inside it.\nThe prompt includes an exact compressed copy of the encoded artifact. The separate artifact file is also included for inspection.\nformat-guide.txt is an optional hint for you. Do not give it to GPT if you want the independent challenge.\nCheck the marked answer in Mirror controls > Decoder challenges; select this challenge from Recent challenges.\nThe answer key expires ${new Date(challenge.expiresAt).toISOString()}, or on Mirror restart/session change. The kit remains usable for independent decoding after expiry.\nNo answer key is included.\n`) },
      );
    }
    // LoaF already produces a standard gzip-compressed USTAR archive before
    // hex wrapping. Reuse that writer for a conventional, easily opened kit.
    const archive = Buffer.from(makeLoaf(entries).split(" ")[1], "hex");
    return reply.header("cache-control", "no-store").header("content-disposition", 'attachment; filename="mirror-decoder-kits.tar.gz"').type("application/gzip").send(archive);
  });
  app.get("/api/decoder-challenges/:id/artifact", async (req, reply) => {
    const { id } = ChallengeParams.parse(req.params);
    const challenge = challenges.get(id);
    if (!challenge || challenge.scope !== scope() || challenge.expiresAt <= Date.now()) {
      return reply.code(404).send({ error: "Challenge expired or unavailable. Generate a new one." });
    }
    const format = formats[challenge.format];
    return reply.header("cache-control", "no-store").header("content-disposition", `attachment; filename="decoder-${id}.${format.extension}"`).type(format.mime).send(challenge.artifact);
  });
  app.post("/api/decoder-challenges/:id/verify", { bodyLimit: 10_000 }, async (req, reply) => {
    const { id } = ChallengeParams.parse(req.params);
    const { hex } = ChallengeAnswer.parse(req.body);
    const challenge = challenges.get(id);
    if (!challenge || challenge.scope !== scope() || challenge.expiresAt <= Date.now()) {
      return reply.code(404).send({ error: "Challenge expired or unavailable. Generate a new one." });
    }
    const actual = Buffer.from(hex, "hex");
    const expected = challenge.expected;
    let matchingBytes = 0;
    for (let i = 0; i < Math.min(expected.length, actual.length); i++) {
      if (expected[i] === actual[i]) matchingBytes++;
    }
    reply.header("cache-control", "no-store");
    return { verdict: actual.equals(expected) ? "exact" : matchingBytes > 0 ? "partial" : "mismatch", matchingBytes, expectedBytes: expected.length, actualBytes: actual.length };
  });
}
